services:
  app:
    container_name: belnetmon_app
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - belnetmon-network

networks:
  belnetmon-network:
    external: true
