services:
  app:
    container_name: belnetmon-app
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@belnetmon-db:5432/belnetmon?schema=public
    networks:
      - belnetmon-network

networks:
  belnetmon-network:
    external: true
