services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: belnetmon-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=belnetmon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5435:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - belnetmon-network

volumes:
  db-data:

networks:
  belnetmon-network:
    external: true
