version: "3"
services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: belnetmon-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=belnetmon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5435:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default
      - belnetmon-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: belnetmon-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db-data:
    driver: local
  pgadmin-data:
    driver: local
networks:
  belnetmon-network:
    external: true
